### ISSUE TITLE
As a participant, when managing emails, I would like to be able to delete emails I am not using

### ISSUE THREAD

**Issue by AnaMickovic** [BPMspaceUG/LIAM2-Client#13]
When participant is registered with min 2 emails, there should be an option to delete emails (please see the photo)
![manage emails- bug - delete email](https://user-images.githubusercontent.com/55175924/66736565-d3914300-ee69-11e9-92b9-e6bebede6789.PNG)

**Comment by bilievskissi** [comment]
I estimate 1 Hour for this.

**Comment by bilievskissi** [comment]
Done in 1 hour.
