### ISSUE TITLE
As a participant, when entering wrong email address while logging in, I woud like following message to be shown

### ISSUE THREAD

**Issue by AnaMickovic** [BPMspaceUG/LIAM2-Client#14]
When wrong email address is entered while logging in, following message should appear instead of current message "wrong email":

"E-mail address is not recognized by the system, please enter the correct e-mail address or register."
![Wrong email_LI](https://user-images.githubusercontent.com/55175924/66993101-506f2780-f0cb-11e9-8a05-34d606b2910f.jpg)

**Comment by bilievskissi** [comment]
Time estimation: 5 minutes.

**Comment by bilievskissi** [comment]
Done in 5 minutes.
