### ISSUE TITLE
As a participant, when I manage my emails, I would like to see "action" buttons for all emails

### ISSUE THREAD

**Issue by AnaMickovic** [BPMspaceUG/LIAM2-Client#15]
- When e-mail is in use only button "do not use" should be visible

- When e-mail is not in use, then both buttons " use" and " delete" should be visible

- IF more e-mails are registered, but only one in use and a Participant clicks on the button "do not use" next to this email, than the Error message should appear: "Minimum one e-email address must be used "

- E-mails can be deleted only if they are not in use

![missing buttons](https://user-images.githubusercontent.com/55175924/66994183-26b70000-f0cd-11e9-9f01-9d4259f72a95.PNG)

**Comment by bilievskissi** [comment]
Time estimation: 30 minutes.

**Comment by bilievskissi** [comment]
Done in 30 minutes.
