### ISSUE TITLE
As a participant, I would like not receive a "warning" message before deleting the registered email

### ISSUE THREAD

**Issue by AnaMickovic** [BPMspaceUG/LIAM2-Client#16]
When managing e-mails while logged in, before deleting the e-mail address Participant needs to receive message:

- IF e-mail is not in use, when clicking on "Delete" button, the following message should appear: " Please confirm that you want to remove this e-mail address" nad bellow the button "Confirm"

IF the e-mail is in use, the "delete" button should not be visible

**Comment by bilievskissi** [comment]
Time estimation: 30 minutes.

**Comment by bilievskissi** [comment]
Done in 30 minutes.
