### ISSUE TITLE
As a Participant, while managing emails, I would like to have "mouse over" buttons

### ISSUE THREAD

**Issue by AnaMickovic** [BPMspaceUG/LIAM2-Client#17]
While managing e-mails, when cursor is postioned on the button, a short explanation of action should appear:
"Do not use" - "Notifications and messages will not be sent to this e-mail address"
"Use" - "Notifications and messages will be sent to this e-mail address"
"Delete" - "This e-mail address will be removed"

**Comment by bilievskissi** [comment]
Time estimation: 30 minutes.

**Comment by bilievskissi** [comment]
Done in 30 minutes.
