### ISSUE TITLE
As a participant, when I forget the password, I would like to thave the possibility to ask for Reset link to be resent

### ISSUE THREAD

**Issue by AnaMickovic** [BPMspaceUG/LIAM2-Client#19]
When participant forgets the password, after entering the e-mail address, the message appears "Password reset link sent to email" and there should be an additional button for "Resend email". 

Also, the text of the message should be revised into "Password reset link is sent to this e-mail address"

**Comment by bilievskissi** [comment]
Time estimation: 30 minutes

**Comment by bilievskissi** [comment]
Done in 30 minutes.
