### ISSUE TITLE
As an organization, I would like that passwords contains minimal security requirements  that also includes creating password history

### ISSUE THREAD

**Issue by AnaMickovic** [BPMspaceUG/LIAM2-Client#4]
When entering the passwort, it must be in minimal lenght and complexity in order to satisfy minimal security requirements: 
- Lower case char;
- Upper case char;
- Numbers;
- Lenght: min 10 caracters

In addition:
- History of old passwords should be kept in hashes used (OWASP recommendations on how to store password hashes securely)

**Comment by bilievskissi** [comment]
About this part:

"History of old passwords should be kept in hashes used (OWASP recommendations on how to store password hashes securely)"

How do you want the passwords stored? Should a new db table be created for the old passwords? Should we keep all passwords, or just the few latest?

**Comment by AnaMickovic** [comment]
@Kuhlig 
can you pease evaluate? when Boban and I discussed this, the recomendation is to have only few latest saved. For DB issues, we need your comment.

Thx
Ana

**Comment by AnaMickovic** [comment]
Hi Boban, I talked to Rob, password history is not MVP, so it is not a priority, so regarding this issue, we need to focus only on security requirements when entering the password.

thx,
Ana

**Comment by bilievskissi** [comment]
Done in 1 hour.
