### ISSUE TITLE
As a participant, I would like to have a possibility to change the password when I forget it

### ISSUE THREAD

**Issue by AnaMickovic** [BPMspaceUG/LIAM2-Client#5]
When participant forgets the password, by clicking on the button "forgot password" and entering the email address, the email with the link to reset the password is sent.

When testing this option the link was not working and I wasn't able to reset the password.

**Comment by bilievskissi** [comment]
Fixed.

**Comment by AnaMickovic** [comment]
For some reason it is not working at all: doesn't recognize emails, and there are no sent email, or message that verification email is sent...

**Comment by AnaMickovic** [comment]
it is working now
